type Rank = 'script-kiddie' | 'junior' | 'mid' | 'senior';

export interface CodewarsTemplate {
  key: string;
  rank: Rank;
  track: string;
  kataTitle: string;
  kataSummary: string;
  stepCardGroups: string[][];
  intensityTier: 1 | 2 | 3 | 4;
}

const T = (rank: Rank, track: string, key: string, kataTitle: string, kataSummary: string, stepCardGroups: string[][], intensityTier: 1 | 2 | 3 | 4): CodewarsTemplate => ({
  key,
  rank,
  track,
  kataTitle,
  kataSummary,
  stepCardGroups,
  intensityTier,
});

export const CODEWARS_TEMPLATES: CodewarsTemplate[] = [
  T(
    'script-kiddie',
    'shell_basics',
    'find_smallest',
    'Find the smallest integer in the array',
    'Read an input stream, keep a rolling minimum, then emit the smallest value safely.',
    [
      ['script_ls'],
      ['script_cat'],
      ['script_grep', 'script_sed'],
      ['fn_set_add', 'fn_map_put'],
      ['syntax_if'],
      ['syntax_return_true', 'syntax_return_false'],
      ['script_cat'],
      ['script_grep'],
      ['script_wash_logs'],
      ['script_scp', 'script_curl'],
    ],
    1,
  ),
  T(
    'script-kiddie',
    'shell_basics',
    'counting_positives_sum_negatives',
    'Counting positives / sum negatives',
    'Partition a noisy payload into counters and aggregate channels without leaking state.',
    [
      ['script_ls'],
      ['script_cat'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['fn_map_put'],
      ['fn_set_add'],
      ['script_grep'],
      ['script_sed'],
      ['script_ping', 'script_nc'],
      ['script_wash_logs'],
    ],
    1,
  ),
  T(
    'junior',
    'strings',
    'disemvowel_trolls',
    'Disemvowel Trolls',
    'Filter all vowels from an incoming text channel while preserving ordering and throughput.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['mid_stream_filter', 'script_grep'],
      ['mid_stream_map', 'script_sed'],
      ['mid_stream_collect', 'script_cat'],
      ['fn_sysout_print', 'lib_commons_blank'],
      ['syntax_return_true', 'syntax_return_false'],
    ],
    2,
  ),
  T(
    'junior',
    'arrays',
    'highest_and_lowest',
    'Highest and Lowest',
    'Parse space separated integers and return max and min in one deterministic response.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_main_method', 'syntax_method_decl'],
      ['syntax_try_catch'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['mid_stream_filter', 'script_grep'],
      ['mid_stream_map'],
      ['mid_stream_collect'],
      ['fn_sysout_print', 'syntax_return_true'],
    ],
    2,
  ),
  T(
    'junior',
    'math',
    'sum_of_odd_numbers',
    'Sum of odd numbers',
    'Build and validate an odd-sequence accumulator for sprint analytics.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_if'],
      ['syntax_foreach'],
      ['fn_map_put'],
      ['mid_stream_init'],
      ['mid_stream_map'],
      ['mid_stream_collect'],
      ['syntax_return_true', 'syntax_return_false'],
    ],
    2,
  ),
  T(
    'mid',
    'data_structures',
    'build_tower',
    'Build Tower',
    'Generate layered output rows with strict width constraints and predictable ordering.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['fn_map_put'],
      ['mid_stream_init'],
      ['mid_stream_map'],
      ['mid_stream_filter'],
      ['mid_stream_collect'],
      ['lib_lombok_builder', 'lib_lombok_data'],
      ['fn_sysout_print'],
    ],
    3,
  ),
  T(
    'mid',
    'parsing',
    'decode_morse',
    'Decode the Morse code',
    'Tokenize encoded packets, map symbols, and reconstruct phrase outputs.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_try_catch'],
      ['syntax_foreach'],
      ['fn_map_put'],
      ['fn_set_add'],
      ['mid_stream_init'],
      ['mid_stream_map'],
      ['mid_stream_collect'],
      ['script_grep', 'script_sed'],
      ['fn_sysout_print'],
    ],
    3,
  ),
  T(
    'mid',
    'validation',
    'valid_braces',
    'Valid Braces',
    'Validate bracket streams with a stack-like contract and early failure exits.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_list_init', 'syntax_set_init'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['fn_set_contains'],
      ['fn_set_add'],
      ['fn_map_put'],
      ['mid_optional'],
      ['syntax_return_true'],
      ['syntax_return_false'],
    ],
    3,
  ),
  T(
    'senior',
    'algorithms',
    'range_extraction',
    'Range Extraction',
    'Compress sorted telemetry into range notation while preserving edge-case semantics.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_try_catch'],
      ['syntax_list_init'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['fn_map_put'],
      ['fn_set_add'],
      ['mid_stream_init'],
      ['mid_stream_filter'],
      ['mid_stream_map'],
      ['mid_stream_collect'],
      ['lib_lombok_builder', 'lib_commons_blank'],
      ['fn_sysout_print'],
      ['syntax_return_true', 'syntax_return_false'],
    ],
    4,
  ),
  T(
    'senior',
    'security',
    'human_readable_duration',
    'Human readable duration format',
    'Normalize and format long-running duration counters for release telemetry.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_try_catch'],
      ['syntax_set_init'],
      ['syntax_list_init'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['fn_map_put'],
      ['fn_set_add'],
      ['mid_stream_init'],
      ['mid_stream_filter'],
      ['mid_stream_map'],
      ['mid_stream_collect'],
      ['lib_lombok_data', 'lib_lombok_builder'],
      ['fn_sysout_print'],
    ],
    4,
  ),
  T(
    'senior',
    'performance',
    'sudoku_solver',
    'Sudoku Solver',
    'Drive constrained search with deterministic branching and rollback-safe state snapshots.',
    [
      ['syntax_package'],
      ['syntax_class_decl'],
      ['syntax_method_decl'],
      ['syntax_try_catch'],
      ['syntax_set_init'],
      ['syntax_list_init'],
      ['syntax_foreach'],
      ['syntax_if'],
      ['fn_map_put'],
      ['fn_set_add'],
      ['fn_set_contains'],
      ['mid_stream_init'],
      ['mid_stream_filter'],
      ['mid_stream_map'],
      ['mid_stream_collect'],
      ['syntax_synchronized', 'lib_network'],
    ],
    4,
  ),
];

