import { MAP_NODES } from './mapData';

export type QuestType = 'talk' | 'combat' | 'delivery' | 'diagnostics';
export type QuestDifficulty = 'quick' | 'standard' | 'hard';

export interface QuestDefinition {
  id: string;
  title: string;
  districtId: string;
  giverNpcId: string;
  description: string;
  objectiveNodeId?: string;
  type: QuestType;
  difficulty: QuestDifficulty;
  tier: number;
  preClassOnly?: boolean;
}
const TYPE_PREFIX: Record<string, string> = {
  combat: 'БОЙ',
  talk: 'СВЯЗЬ',
  delivery: 'ДОСТ',
  diagnostics: 'ДИАГ'
};

const NPC_QUEST_BLUEPRINTS = [
  {
    suffix: 'signal_sweep',
    title: 'Прочес сети',
    type: 'diagnostics' as const,
    difficulty: 'quick' as const,
    text: 'Сними показания с узлов и верни короткий отчёт.',
  },
  {
    suffix: 'local_contract',
    title: 'Локальный контракт',
    type: 'talk' as const,
    difficulty: 'standard' as const,
    text: 'Собери требования заказчика и закрой тикет без эскалации.',
  },
];

const COMBAT_QUEST_BLUEPRINTS = [
  {
    suffix: 'bug_sweep',
    title: 'Зачистка бага',
    type: 'combat' as const,
    difficulty: 'standard' as const,
    text: 'Подави нестабильный узел в районе и стабилизируй сервис.',
  },
  {
    suffix: 'secure_delivery',
    title: 'Безопасная доставка',
    type: 'delivery' as const,
    difficulty: 'hard' as const,
    text: 'Доставь пакет через враждебный сегмент без потери данных.',
  },
];

function buildNpcQuests() {
  const quests: QuestDefinition[] = [];
  for (const district of MAP_NODES) {
    const npcs = district.subNodes?.filter((s) => s.type === 'npc') ?? [];
    for (const npc of npcs) {
      NPC_QUEST_BLUEPRINTS.forEach((b, idx) => {
        quests.push({
          id: `q_${district.id}_${npc.id}_${b.suffix}`,
          title: `[${TYPE_PREFIX[b.type] || '????'}] ${b.title}: ${npc.name}`,
          districtId: district.id,
          giverNpcId: npc.id,
          description: b.text,
          type: b.type,
          difficulty: b.difficulty,
          tier: district.tier,
          preClassOnly: idx === 0,
        });
      });
    }
  }
  return quests;
}

function buildCombatDistrictQuests() {
  const quests: QuestDefinition[] = [];
  for (const district of MAP_NODES) {
    const combats = district.subNodes?.filter((s) => s.type === 'combat') ?? [];
    for (const node of combats) {
      COMBAT_QUEST_BLUEPRINTS.forEach((b, idx) => {
        quests.push({
          id: `q_${district.id}_${node.id}_${b.suffix}`,
          title: `[${TYPE_PREFIX[b.type] || '????'}] ${b.title}: ${node.name}`,
          districtId: district.id,
          giverNpcId: (district.subNodes?.find((s) => s.type === 'npc')?.id ?? node.id),
          objectiveNodeId: node.id,
          description: b.text,
          type: b.type,
          difficulty: b.difficulty,
          tier: district.tier,
          preClassOnly: idx === 0,
        });
      });
    }
  }
  return quests;
}

const TUTORIAL_QUESTS: QuestDefinition[] = [
  {
    id: 'q_kiddo_start',
    title: '[ВВОД] Пробуждение в Altufyevo',
    description: 'Не знаешь что делать? Поговори с Петровичем в "Синем Чипе", он направит.',
    districtId: 'altufyevo',
    giverNpcId: 'job_board_alt',
    type: 'talk',
    objectiveNodeId: 'npc_petrovich',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_kiddo_first_bits',
    title: '[ВВОД] Первые Bits',
    description: 'Петрович не работает бесплатно. Найди Доску Объявлений в Алтуфьево и заверши простейший контракт на чистку кэша.',
    districtId: 'altufyevo',
    giverNpcId: 'job_board_alt',
    objectiveNodeId: 'combat_rats', // Changed to the actual combat node
    type: 'combat',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_altufyevo_data_leak',
    title: 'Утечка пакетов L1',
    description: 'Обнаружена потеря пакетов данных рядом с узлом Синего Чипа. Требуется провести диагностику сети.',
    districtId: 'altufyevo',
    giverNpcId: 'job_board_alt',
    objectiveNodeId: 'bar_chips', // Players have to go to Blue Chip bar area for diagnostics
    type: 'diagnostics',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_altufyevo_scrap_hunt',
    title: 'Охота за Восходом',
    description: 'Серый просит добыть процессоры с ботов "Восход" на Свалке.',
    districtId: 'altufyevo',
    giverNpcId: 'shop_scrap',
    objectiveNodeId: 'combat_nixanna_ritual', // Let's pretend they spawn near the Ritual node
    type: 'combat',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_kiddo_metro_access',
    title: '[ВВОД] Путь в Центр',
    description: 'Чтобы покинуть окраины, тебе нужен доступ к Такси. Собери 100 Bits и разблокируй терминал в Алтуфьево.',
    districtId: 'altufyevo',
    giverNpcId: 'term_taxi_alt',
    objectiveNodeId: 'term_taxi_alt',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_trainee_exam_theory',
    title: '[ЭКЗАМЕН] Теория Архитектуры',
    description: 'Найди Профессора Архипова на Юго-Западной. Он проверит твои знания основ перед тем, как допустить к Боевому Экзамену.',
    districtId: 'south_west',
    giverNpcId: 'npc_professor',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_trainee_exam_practice',
    title: '[ЭКЗАМЕН] Боевой Диплом',
    description: 'Финальный этап. Докажи Профессору, что ты можешь не только рассуждать о Java, но и дебажить реальность. Победи тренировочного бота на ВДНХ.',
    districtId: 'vdnkh',
    giverNpcId: 'npc_besm',
    objectiveNodeId: 'combat_pavilions',
    type: 'combat',
    difficulty: 'hard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_academy_combat_training',
    title: '[ПРАКТИКА] Боевой Дибаг',
    description: 'Тьютор-бот "Индекс" вызвал тебя на учебный поединок. Победи Тренировочного Манекена, чтобы подтвердить свою квалификацию.',
    districtId: 'academy',
    giverNpcId: 'npc_academy_tutor',
    objectiveNodeId: 'combat_tutorial_dummy',
    type: 'combat',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_maryino_qa_audit',
    title: '[QUAD] Аудит безопасности',
    description: 'Trace (QA) просит собрать дампы с трех терминалов в секторе и проверить их на наличие аномалий в заголовках. Награда: 50 Bits.',
    districtId: 'maryino',
    giverNpcId: 'npc_tanya',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_maryino_scrap_raid',
    title: '[VOID] Рейд за деталями',
    description: 'Крыса-курьер наводку на склад Federal Oversight. Нужно зайти и "приватизировать" пару модулей памяти. Ожидается сопротивление.',
    districtId: 'maryino',
    giverNpcId: 'npc_rat',
    objectiveNodeId: 'combat_local_lan',
    type: 'combat',
    difficulty: 'hard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_maryino_shluz_repair',
    title: '[RPG] Ремонт шлюза',
    description: 'Сержант сообщает, что система авторизации на южном шлюзе "зависла". Нужно вручную обнулить триггер в консоли управления.',
    districtId: 'maryino',
    giverNpcId: 'npc_sarge',
    type: 'talk',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_maryino_terminal_404',
    title: '[TECH] Восстановление 404',
    description: 'Терминал #404 содержит битые сектора. Если вы сможете восстановить таблицу разделов, вы получите доступ к скрытым архивам Анархистов.',
    districtId: 'maryino',
    giverNpcId: 'term_404',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_maryino_passage',
    title: '[RPG] Переправа: Марьино',
    description: 'Для свободного прохода через южные узлы нужно договориться с группировкой "Восход". Начни с Крысы-курьера, он знает, кто здесь держит улицу.',
    districtId: 'maryino',
    giverNpcId: 'npc_rat',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_professor_garbage',
    title: '[АКАДЕМИЯ] Сборка мусора',
    description: 'В Мейнфрейме Университета скопилось слишком много "битых ссылок". Профессор просит провести ручную дефрагментацию и очистку памяти.',
    districtId: 'south_west',
    giverNpcId: 'npc_professor',
    objectiveNodeId: 'combat_academic_guard',
    type: 'combat',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: false,
  },
  {
    id: 'q_trace_stress_test',
    title: '[QUAD] Стресс-тест сети',
    description: 'Trace (QA) из Марьино требует провести принудительный прозвон (ping) локальных узлов. Пакеты теряются, и нужно выяснить, где именно происходит затык.',
    districtId: 'maryino',
    giverNpcId: 'npc_tanya',
    objectiveNodeId: 'combat_local_lan',
    type: 'combat',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_rat_data_dump',
    title: '[VOID] Нелегальный дамп',
    description: 'Крыса-курьер хочет, чтобы вы отбили серверную ферму в "Buffer Overflow Zone". Там спрятаны ценные данные Анархистов.',
    districtId: 'maryino',
    giverNpcId: 'npc_rat',
    objectiveNodeId: 'combat_overflow',
    type: 'combat',
    difficulty: 'hard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_besm_vintage_code',
    title: '[RPG] Винтажный код',
    description: 'Генерал БЭСМ ищет драйверы для своей архитектуры 1974 года. Попробуйте найти их у Скупщика на рынке в Измайлово.',
    districtId: 'vdnkh',
    giverNpcId: 'npc_besm',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_monya_signal_echo',
    title: '[RPG] Эхо сигнала',
    description: 'Связист Моня из Бибирево жалуется на помехи. Гид в ВДНХ может знать о старых зонах радиомолчания в этом районе.',
    districtId: 'bibirevo',
    giverNpcId: 'npc_signalman',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_verstak_cooling',
    title: '[DELIVERY] Хладагент для Верстака',
    description: 'Мастеру Верстаку из Измайлово нужен технический хладагент. Его можно достать у Крысы-курьера в Марьино.',
    districtId: 'izmailovo',
    giverNpcId: 'npc_master',
    type: 'delivery',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_niksanna_recommendation',
    title: '[TALK] Рекомендация в Академию',
    description: 'Никсанна хочет, чтобы вы пошли в Академию. Обратитесь к Профессору Архипову в Юго-Западном секторе с её "визуальным образцом".',
    districtId: 'altufyevo',
    giverNpcId: 'npc_niksanna',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_altufyevo_data_leak',
    title: '[REPAIR] Утечка в распредщите',
    description: 'Узел связи в Алтуфьево коротит на массу. Нужно найти распредщит и принудительно патчить изоляцию протокола.',
    districtId: 'altufyevo',
    giverNpcId: 'job_board_alt',
    type: 'talk',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_altufyevo_silo_scout',
    title: '[SCAN] Тепловая карта Силоса 7',
    description: 'Варвару нужны данные о температуре в 7-м силосе. Литейные цени перекрыты, но консоль в Силосе №7 всё еще доступна для ручной диагностики.',
    districtId: 'altufyevo',
    giverNpcId: 'npc_varvar',
    objectiveNodeId: 'term_silo_7',
    type: 'diagnostics',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_altufyevo_scrap_hunt',
    title: '[COMBAT] Охота за хламом',
    description: 'Скупщику нужны запчасти от ботов "Восход". Отправься в зону Свалки и добудь пару рабочих процессоров.',
    districtId: 'altufyevo',
    giverNpcId: 'shop_scrap',
    objectiveNodeId: 'combat_rats',
    type: 'combat',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_altufyevo_varvar_backup',
    title: '[DELIVERY] Доставка бэкапа',
    description: 'Варвару нужно передать зашифрованный бэкап Связисту Моне в Бибирево. Это старый долг по коду.',
    districtId: 'altufyevo',
    giverNpcId: 'npc_varvar',
    type: 'delivery',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_weaver_pattern',
    title: '[DELIVERY] Паттерн Ткача',
    description: 'Старшему Ткачу из Текстильщиков нужен старый промышленный паттерн. Он должен быть в архивах Академии на Юго-Западе.',
    districtId: 'tekstilschiki',
    giverNpcId: 'npc_weaver_senior',
    type: 'delivery',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: false,
  },
  {
    id: 'q_vykhino_delivery',
    title: '[DELIVERY] Опечатанный архив',
    description: 'Грузчик из Выхино просит доставить тяжелый опечатанный блок данных Петровичу в Алтуфьево. Будьте осторожны на перегонах.',
    districtId: 'vykhino',
    giverNpcId: 'npc_vykhino_loader',
    type: 'delivery',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_vykhino_subway_leak',
    title: '[REPAIR] Сигнал перегона',
    description: 'Менеджер каналов сообщает о рассинхронизации сигналов на путях. Нужно найти релейный шкаф и обновить прошивку.',
    districtId: 'vykhino',
    giverNpcId: 'npc_link_manager',
    type: 'talk',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_vykhino_audit_evasion',
    title: '[TECH] Чистка логов аудита',
    description: 'Грей хочет, чтобы вы пробрались к центральному терминалу и удалили логи посещений за последние 24 часа. Аудиторы GigaBank наступают на пятки.',
    districtId: 'vykhino',
    giverNpcId: 'npc_grey',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_vykhino_transit_tax',
    title: '[TALK] Сбор дебита',
    description: 'Фиксер Батя просит напомнить бармену в "Транзите", что за безопасность нужно платить. Соберите долю и вернитесь к Бате.',
    districtId: 'vykhino',
    giverNpcId: 'npc_job_boss',
    type: 'talk',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_vykhino_corp_favor',
    title: '[SCAN] Корпоративный шпионаж',
    description: 'Скаут GigaBank обещает бонусы за сканирование частот, на которых общаются Redundants. Нужно найти их "тихий" узел.',
    districtId: 'vykhino',
    giverNpcId: 'npc_corp_scout',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_chertanovo_privacy',
    title: '[TALK] Протокол приватности',
    description: 'Параноидальному жителю Чертаново нужен "Privacy Patch". Никсанна из Алтуфьево — единственный мастер, кто может его собрать.',
    districtId: 'chertanovo',
    giverNpcId: 'npc_chertanovo_paranoid',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_sokolniki_haunted_logs',
    title: '[VOID] Призрак в машине: Сокольники',
    description: 'В заброшенной лаборатории Сокольников проснулся древний ИИ-ассистент. Он бредит и спамит в сеть фрагментами удаленных логов. Нужно либо упокоить его, либо вылечить.',
    districtId: 'sokolniki',
    giverNpcId: 'npc_ghost_server',
    type: 'talk',
    difficulty: 'hard',
    tier: 2,
    preClassOnly: false,
  },
  {
    id: 'q_fili_media_leak',
    title: '[MEDIA] Утечка на Орбите: Фили',
    description: 'Эхо (медиа-брокер) ищет "жареные" факты о слиянии корпораций. Спутник перехватил поток данных, но он зашифрован ключом 4-й категории.',
    districtId: 'fili',
    giverNpcId: 'npc_echo_broker',
    type: 'talk',
    difficulty: 'standard',
    tier: 4,
    preClassOnly: false,
  },
  {
    id: 'q_mitino_black_market_ping',
    title: '[VOID] Прозвон черного рынка: Митино',
    description: 'Теневой Скупщик хочет проверить стабильность скрытых каналов связи перед крупной сделкой. Нужно провести серию скрытых "пингов" без привлечения внимания Регуляторов.',
    districtId: 'mitino',
    giverNpcId: 'npc_market_shady',
    type: 'talk',
    difficulty: 'quick',
    tier: 2,
    preClassOnly: false,
  },
  {
    id: 'q_perovo_combat_commissar_redistribution',
    title: '[RED] Экспроприация данных',
    description: 'Комиссар Байт требует перехватить конвой Gigabank и обнулить долговые реестры жителей Перово. Это удар по самому сердцу финансовой диктатуры.',
    districtId: 'perovo',
    giverNpcId: 'npc_commissar_byte',
    objectiveNodeId: 'perovo_shluze_4', 
    type: 'combat',
    difficulty: 'hard',
    tier: 3,
    preClassOnly: false,
  },
  {
    id: 'q_academy_student_research',
    title: '[SCAN] Сбор данных для курсовой',
    description: 'Студент-Прикладник в Академии просит собрать три дампа с внешних узлов для его работы по низкоуровневым протоколам.',
    districtId: 'academy',
    giverNpcId: 'npc_academy_student',
    type: 'diagnostics',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_chertanovo_find_zero',
    title: '[TALK] Поиск Z3R0',
    description: 'Глюк в Чертаново упомянул некоего Z3R0, который "видит пустоту". Нужно найти его в этом районе.',
    districtId: 'chertanovo',
    giverNpcId: 'npc_glitch',
    type: 'talk',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_sokol_talk_lab_delivery',
    title: '[ДОСТ] Методички по Ассемблеру',
    description: 'Лаборант Илья просит доставить учебные материалы Профессору Архипову. Простое задание для укрепления репутации.',
    districtId: 'sokol',
    giverNpcId: 'npc_lab_assistant',
    type: 'delivery',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_sokol_combat_drone_training',
    title: '[БОЙ] Тренировочный полет',
    description: 'Пилот Дронов готов провести учебный спарринг. Попробуй выжить под натиском легких дронов.',
    districtId: 'sokol',
    giverNpcId: 'npc_drone_pilot',
    type: 'combat',
    difficulty: 'quick',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_sokol_fetch_chip_quest',
    title: '[TECH] Поиск чипа "Стриж-4"',
    description: 'Инженер ищет редкий чип управления. Спроси у Семёныча, он знает все свалки Сокола.',
    districtId: 'sokol',
    giverNpcId: 'npc_avionics_dev',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_bibirevo_energy',
    title: '[RPG] Энергия для Кодера',
    description: 'Сонный Кодер в Бибирево засыпает на ходу. Ему нужен особый чай "Дзен-Лог" от Олега на ВДНХ.',
    districtId: 'bibirevo',
    giverNpcId: 'npc_bibirevo_coder',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_sokolniki_herb_data',
    title: '[SCAN] Био-ритмы леса',
    description: 'Друиду Арборису нужны данные о чистоте почвы в Сокольниках. Просканируй три точки и вернись к нему.',
    districtId: 'sokolniki',
    giverNpcId: 'npc_druid_coder',
    type: 'diagnostics',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_fili_satellite_interception',
    title: '[MEDIA] Орбитальный перехват',
    description: 'Луна из Фили пытается поймать сигнал со старого спутника. Ей нужна помощь с релейным оборудованием из Митино.',
    districtId: 'fili',
    giverNpcId: 'npc_orbit_stalker',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_mitino_radio_relay',
    title: '[TECH] Радио-реле Дяди Вани',
    description: 'Дядя Ваня в Митино готов собрать реле, но ему не хватает запчастей. Нужно найти Флэша.',
    districtId: 'mitino',
    giverNpcId: 'npc_radio_ham',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_mitino_hardware_mod',
    title: '[TECH] Тюнинг Флэша',
    description: 'Флэш может разогнать реле, если ты поможешь ему с тестами на Свалке.',
    districtId: 'mitino',
    giverNpcId: 'npc_hardware_modder',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_fili_audit_logs',
    title: '[ADMIN] Логи Архивариуса',
    description: 'Архивариус в Фили нашел странные записи в логах. Их нужно передать Аудитору в Таганку для расшифровки.',
    districtId: 'fili',
    giverNpcId: 'npc_archivist',
    type: 'delivery',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_taganka_bribe_negotiation',
    title: '[CORP] Переговоры в Таганке',
    description: 'Аудитор в Таганке не хочет делиться инфой бесплатно. Нужно либо заплатить, либо найти компромат.',
    districtId: 'taganka',
    giverNpcId: 'npc_auditor',
    type: 'talk',
    difficulty: 'hard',
    tier: 2,
    preClassOnly: true,
  },
  {
    id: 'q_hub_signature',
    title: '[TALK] Подпись Петровича',
    description: 'Для обхода системы в Таганке нужна цифровая подпись Петровича из Хаба.',
    districtId: 'hub',
    giverNpcId: 'npc_petrovich',
    type: 'talk',
    difficulty: 'quick',
    tier: 2,
    preClassOnly: true,
  },
  {
    id: 'q_mitino_debt',
    title: '[VOID] Долги Митино',
    description: 'Флэш задолжал Барыге Мише. Нужно либо отдать Bits, либо отработать на Свалке.',
    districtId: 'mitino',
    giverNpcId: 'npc_hardware_modder',
    type: 'talk',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
  {
    id: 'q_altufyevo_silo_clear',
    title: '[ВВОД] Зачистка Силоса 7',
    description: 'Петрович говорит, что системы охлаждения шумят из-за стаи крыс-кодеров. Помоги ему стабилизировать узел в зоне "СИЛОС №7: ВНУТРЕННИЙ КОНТУР".',
    districtId: 'altufyevo',
    giverNpcId: 'npc_petrovich',
    objectiveNodeId: 'combat_silo_inner',
    type: 'combat',
    difficulty: 'standard',
    tier: 1,
    preClassOnly: true,
  },
];

export const QUEST_LIBRARY: QuestDefinition[] = [
  ...TUTORIAL_QUESTS,
  ...buildNpcQuests(), 
  ...buildCombatDistrictQuests()
];
